shader_type spatial;
render_mode cull_disabled;

uniform float size_small = 0.02;
uniform float size_large = 0.04;

uniform float blade_bend = 0.3;

uniform vec3 color_small: source_color = vec3(0.25, 0.55, 0.12);
uniform vec3 color_large: source_color = vec3(0.4, 0.65, 0.15);

uniform sampler2D patch_noise;
uniform float patch_scale = 7.0;
varying float patch_factor;

uniform sampler2D wind_noise;
uniform float wind_strength = 0.04;
uniform vec2 wind_direction = vec2(1.0, 0.0);
uniform float wind_bend_strength = 2.0;
uniform float wind_ao_affect = 1.0;

varying float bottom_to_top;
varying float current_wind_bend;

void vertex() {
	bottom_to_top = 1.0 - UV.y;

	vec2 wind_position = NODE_POSITION_WORLD.xz / 10.0;
	wind_position -= TIME * wind_direction * wind_strength;

	current_wind_bend = texture(wind_noise, wind_position).x;
	current_wind_bend *= wind_strength;
	current_wind_bend *= bottom_to_top * 2.0;

	mat4 inv_model = inverse(MODEL_MATRIX);
	vec2 local_direction = (inv_model * vec4(wind_direction.x, 0.0, wind_direction.y, 0.0)).xz;

	VERTEX.xz += current_wind_bend * local_direction * wind_bend_strength;

	VERTEX.z += blade_bend * pow(bottom_to_top, 2.0);

	patch_factor = texture(patch_noise, NODE_POSITION_WORLD.xz / patch_scale).r;
	VERTEX *= mix(size_small, size_large, patch_factor);

	NORMAL = mix(NORMAL, vec3(0.0, 1.0, 0.0), bottom_to_top);
}

void fragment() {
	AO = bottom_to_top - current_wind_bend * wind_ao_affect;
	AO_LIGHT_AFFECT = 1.0;

	ALBEDO = mix(color_small, color_large, patch_factor);
	BACKLIGHT = vec3(0.2);

	ROUGHNESS = 0.4;
	SPECULAR = 0.2;
}
